version: '3.8'
services:
  orchestrator:
    build: ./src/orchestrator
    ports:
      - "8000:8000"
    depends_on:
      - planner
      - osint_agent
      - phishing_agent
      - social_engineer_agent
      - data_collector
      - persona_manager

  planner:
    build: ./src/planner
    ports:
      - "8001:8001"
    depends_on:
      - persona_manager

  osint_agent:
    build: ./src/agents/osint_agent
    ports:
      - "8010:8010"

  phishing_agent:
    build: ./src/agents/phishing_agent
    ports:
      - "8011:8011"

  social_engineer_agent:
    build: ./src/agents/social_engineer_agent
    ports:
      - "8012:8012"

  data_collector:
    build: ./src/agents/data_collector
    ports:
      - "8013:8013"

  persona_manager:
    build: ./src/persona_manager
    ports:
      - "8020:8020"
    volumes:
      - ./data/personas:/app/avatars
